### PR TITLE
[REVIEW] Fix conda deps and build script, add test skipping functionality to build script

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Depends on https://github.com/rapidsai/ops/issues/186

### CODE REVIEW

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Review by dantegd — APPROVED** [review]

**Review by cjnolet — APPROVED** [review]
LGTM!

**Pull request merged**
