### PR TITLE
[REVIEW] Fix gpu build script

### PR DESCRIPTION
**Pull request by dillon-cullinan**

### CODE REVIEW

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Pull request merged**
